[theme]
base = "dark"
primaryColor = "#2563EB"
backgroundColor = "#0F172A"       # Navy Gelap untuk Latar Belakang Utama
secondaryBackgroundColor = "#1E293B" # Navy Sedikit Lebih Terang untuk Sidebar
textColor = "#F8FAFC"             # Teks Putih Terang